# Generated by cpp11: do not edit by hand

mode_mipodinmodel_alloc <- function(r_pars, time, n_particles, n_threads, control, seed) {
  .Call(`_mipodinmodel85dc80d9_mode_mipodinmodel_alloc`, r_pars, time, n_particles, n_threads, control, seed)
}

mode_mipodinmodel_control <- function(ptr) {
  .Call(`_mipodinmodel85dc80d9_mode_mipodinmodel_control`, ptr)
}

mode_mipodinmodel_time <- function(ptr) {
  .Call(`_mipodinmodel85dc80d9_mode_mipodinmodel_time`, ptr)
}

mode_mipodinmodel_run <- function(ptr, end_time) {
  .Call(`_mipodinmodel85dc80d9_mode_mipodinmodel_run`, ptr, end_time)
}

mode_mipodinmodel_state_full <- function(ptr) {
  .Call(`_mipodinmodel85dc80d9_mode_mipodinmodel_state_full`, ptr)
}

mode_mipodinmodel_state <- function(ptr, index) {
  .Call(`_mipodinmodel85dc80d9_mode_mipodinmodel_state`, ptr, index)
}

mode_mipodinmodel_stats <- function(ptr) {
  .Call(`_mipodinmodel85dc80d9_mode_mipodinmodel_stats`, ptr)
}

mode_mipodinmodel_update_state <- function(ptr, pars, time, state, index, set_initial_state, reset_step_size) {
  .Call(`_mipodinmodel85dc80d9_mode_mipodinmodel_update_state`, ptr, pars, time, state, index, set_initial_state, reset_step_size)
}

mode_mipodinmodel_set_index <- function(ptr, index) {
  invisible(.Call(`_mipodinmodel85dc80d9_mode_mipodinmodel_set_index`, ptr, index))
}

mode_mipodinmodel_set_stochastic_schedule <- function(ptr, time) {
  invisible(.Call(`_mipodinmodel85dc80d9_mode_mipodinmodel_set_stochastic_schedule`, ptr, time))
}

mode_mipodinmodel_n_variables <- function(ptr) {
  .Call(`_mipodinmodel85dc80d9_mode_mipodinmodel_n_variables`, ptr)
}

mode_mipodinmodel_n_state_run <- function(ptr) {
  .Call(`_mipodinmodel85dc80d9_mode_mipodinmodel_n_state_run`, ptr)
}

mode_mipodinmodel_n_state_full <- function(ptr) {
  .Call(`_mipodinmodel85dc80d9_mode_mipodinmodel_n_state_full`, ptr)
}

mode_mipodinmodel_reorder <- function(ptr, index) {
  invisible(.Call(`_mipodinmodel85dc80d9_mode_mipodinmodel_reorder`, ptr, index))
}

mode_mipodinmodel_set_n_threads <- function(ptr, n_threads) {
  invisible(.Call(`_mipodinmodel85dc80d9_mode_mipodinmodel_set_n_threads`, ptr, n_threads))
}

mode_mipodinmodel_has_openmp <- function() {
  .Call(`_mipodinmodel85dc80d9_mode_mipodinmodel_has_openmp`)
}
