# Generated by cpp11: do not edit by hand

mode_odinmodel_alloc <- function(r_pars, time, n_particles, n_threads, control, seed) {
  .Call(`_odinmodel55130259_mode_odinmodel_alloc`, r_pars, time, n_particles, n_threads, control, seed)
}

mode_odinmodel_control <- function(ptr) {
  .Call(`_odinmodel55130259_mode_odinmodel_control`, ptr)
}

mode_odinmodel_time <- function(ptr) {
  .Call(`_odinmodel55130259_mode_odinmodel_time`, ptr)
}

mode_odinmodel_run <- function(ptr, end_time) {
  .Call(`_odinmodel55130259_mode_odinmodel_run`, ptr, end_time)
}

mode_odinmodel_state_full <- function(ptr) {
  .Call(`_odinmodel55130259_mode_odinmodel_state_full`, ptr)
}

mode_odinmodel_state <- function(ptr, index) {
  .Call(`_odinmodel55130259_mode_odinmodel_state`, ptr, index)
}

mode_odinmodel_stats <- function(ptr) {
  .Call(`_odinmodel55130259_mode_odinmodel_stats`, ptr)
}

mode_odinmodel_update_state <- function(ptr, pars, time, state, index, set_initial_state, reset_step_size) {
  .Call(`_odinmodel55130259_mode_odinmodel_update_state`, ptr, pars, time, state, index, set_initial_state, reset_step_size)
}

mode_odinmodel_set_index <- function(ptr, index) {
  invisible(.Call(`_odinmodel55130259_mode_odinmodel_set_index`, ptr, index))
}

mode_odinmodel_set_stochastic_schedule <- function(ptr, time) {
  invisible(.Call(`_odinmodel55130259_mode_odinmodel_set_stochastic_schedule`, ptr, time))
}

mode_odinmodel_n_variables <- function(ptr) {
  .Call(`_odinmodel55130259_mode_odinmodel_n_variables`, ptr)
}

mode_odinmodel_n_state_run <- function(ptr) {
  .Call(`_odinmodel55130259_mode_odinmodel_n_state_run`, ptr)
}

mode_odinmodel_n_state_full <- function(ptr) {
  .Call(`_odinmodel55130259_mode_odinmodel_n_state_full`, ptr)
}

mode_odinmodel_reorder <- function(ptr, index) {
  invisible(.Call(`_odinmodel55130259_mode_odinmodel_reorder`, ptr, index))
}

mode_odinmodel_set_n_threads <- function(ptr, n_threads) {
  invisible(.Call(`_odinmodel55130259_mode_odinmodel_set_n_threads`, ptr, n_threads))
}

mode_odinmodel_has_openmp <- function() {
  .Call(`_odinmodel55130259_mode_odinmodel_has_openmp`)
}
